const CONNECTIONS_GROUPS = [
  { "category": "Scripting Languages", "words": ["Python", "Ruby", "Perl", "Lua"], "difficulty": "yellow" },
  { "category": "Compiled Languages", "words": ["C", "C++", "Rust", "Go"], "difficulty": "green" },
  { "category": "Web Languages", "words": ["HTML", "CSS", "JavaScript", "TypeScript"], "difficulty": "yellow" },
  { "category": "JVM Languages", "words": ["Java", "Kotlin", "Scala", "Clojure"], "difficulty": "green" },
  { "category": "Functional Languages", "words": ["Haskell", "Elixir", "F#", "OCaml"], "difficulty": "blue" },
  { "category": "Low-Level Languages", "words": ["Assembly", "C", "Fortran", "COBOL"], "difficulty": "blue" },
  { "category": "Microsoft Ecosystem", "words": ["C#", "PowerShell", "VB.NET", "F#"], "difficulty": "green" },
  { "category": "Mobile Languages", "words": ["Swift", "Objective-C", "Java", "Kotlin"], "difficulty": "green" },
  { "category": "AI/ML Languages", "words": ["Python", "R", "Julia", "Lisp"], "difficulty": "blue" },
  { "category": "Types of Malware", "words": ["Virus", "Worm", "Trojan", "Ransomware"], "difficulty": "yellow" },
  { "category": "Hacking Tools", "words": ["Metasploit", "Nmap", "Wireshark", "Burp Suite"], "difficulty": "blue" },
  { "category": "Encryption Types", "words": ["AES", "RSA", "SHA-256", "Blowfish"], "difficulty": "green" },
  { "category": "Cyber Attacks", "words": ["DDoS", "Phishing", "MITM", "SQL Injection"], "difficulty": "yellow" },
  { "category": "Security Roles", "words": ["Analyst", "Pentester", "CISO", "SOC Operator"], "difficulty": "blue" },
  { "category": "Binary Values", "words": ["0001", "0101", "1010", "1111"], "difficulty": "yellow" },
  { "category": "Logic Gates", "words": ["AND", "OR", "XOR", "NAND"], "difficulty": "yellow" },
  { "category": "Number Systems", "words": ["Binary", "Hex", "Octal", "Decimal"], "difficulty": "yellow" },
  { "category": "Bitwise Ops", "words": ["SHIFT", "AND", "OR", "XOR"], "difficulty": "green" },
  { "category": "Networking Devices", "words": ["Router", "Switch", "Firewall", "Access Point"], "difficulty": "yellow" },
  { "category": "IP Types", "words": ["Static", "Dynamic", "Public", "Private"], "difficulty": "yellow" },
  { "category": "Protocols", "words": ["TCP", "UDP", "FTP", "HTTP"], "difficulty": "yellow" },
  { "category": "OSI Layers", "words": ["Transport", "Network", "Physical", "Session"], "difficulty": "green" },
  { "category": "Storage Types", "words": ["HDD", "SSD", "Flash", "Tape"], "difficulty": "yellow" },
  { "category": "Memory", "words": ["RAM", "ROM", "Cache", "Registers"], "difficulty": "green" },
  { "category": "CPU Components", "words": ["ALU", "CU", "Cache", "Registers"], "difficulty": "green" },
  { "category": "Computer Peripherals", "words": ["Mouse", "Keyboard", "Monitor", "Printer"], "difficulty": "yellow" },
  { "category": "SDLC Phases", "words": ["Plan", "Design", "Develop", "Test"], "difficulty": "yellow" },
  { "category": "Agile Roles", "words": ["Scrum Master", "Product Owner", "Dev Team", "Stakeholder"], "difficulty": "blue" },
  { "category": "Agile Ceremonies", "words": ["Sprint", "Standup", "Review", "Retro"], "difficulty": "green" },
  { "category": "SQL Commands", "words": ["SELECT", "INSERT", "UPDATE", "DELETE"], "difficulty": "yellow" },
  { "category": "Database Types", "words": ["Relational", "NoSQL", "Graph", "Key-Value"], "difficulty": "green" },
  { "category": "DB Index Types", "words": ["B-Tree", "Hash", "Bitmap", "GIN"], "difficulty": "blue" },
  { "category": "ML Types", "words": ["Supervised", "Unsupervised", "Reinforcement", "Self-Supervised"], "difficulty": "green" },
  { "category": "Neural Network Types", "words": ["CNN", "RNN", "GAN", "Transformer"], "difficulty": "blue" },
  { "category": "AI Terms", "words": ["Token", "Embedding", "Parameter", "Gradient"], "difficulty": "blue" },
  { "category": "OS Types", "words": ["Windows", "Linux", "Unix", "MacOS"], "difficulty": "yellow" },
  { "category": "Scheduling Algorithms", "words": ["Round Robin", "FCFS", "SJF", "Priority"], "difficulty": "blue" },
  { "category": "File Systems", "words": ["NTFS", "FAT32", "EXT4", "APFS"], "difficulty": "green" },
  { "category": "Sorting Algorithms", "words": ["Bubble Sort", "Merge Sort", "Quick Sort", "Selection Sort"], "difficulty": "yellow" },
  { "category": "Searching Algorithms", "words": ["Binary Search", "Linear Search", "DFS", "BFS"], "difficulty": "green" },
  { "category": "Graph Algorithms", "words": ["Dijkstra", "Kruskal", "Prim", "Bellman-Ford"], "difficulty": "blue" },
  { "category": "Greedy Algorithms", "words": ["Huffman", "Activity Selection", "Coin Change", "Interval Scheduling"], "difficulty": "blue" },
  { "category": "Dynamic Programming", "words": ["Knapsack", "LCS", "Floyd-Warshall", "Matrix Chain"], "difficulty": "purple" },
  { "category": "String Algorithms", "words": ["KMP", "Rabin-Karp", "Trie", "Z-Algorithm"], "difficulty": "purple" },
  { "category": "Tree Types", "words": ["BST", "AVL", "Red-Black", "B-Tree"], "difficulty": "blue" },
  { "category": "Hashing Concepts", "words": ["Hash Table", "Collision", "Chaining", "Open Addressing"], "difficulty": "green" },
  { "category": "Big-O", "words": ["O(1)", "O(n)", "O(n log n)", "O(n^2)"], "difficulty": "green" },
  { "category": "Cloud Models", "words": ["IaaS", "PaaS", "SaaS", "FaaS"], "difficulty": "green" },
  { "category": "DevOps Tools", "words": ["Docker", "Kubernetes", "Jenkins", "Terraform"], "difficulty": "green" },
  { "category": "Programming Paradigms", "words": ["OOP", "Functional", "Procedural", "Declarative"], "difficulty": "yellow" },
  { "category": "APIs & Protocols", "words": ["REST", "GraphQL", "gRPC", "SOAP"], "difficulty": "green" },
  { "category": "Version Control", "words": ["Git", "Commit", "Branch", "Merge"], "difficulty": "yellow" },
  { "category": "Popular Libraries", "words": ["React", "Vue", "NumPy", "Pandas"], "difficulty": "green" },
  { "category": "Computer Architecture", "words": ["Pipeline", "Registers", "Cache", "Instruction Set"], "difficulty": "blue" },
  { "category": "Networking Concepts", "words": ["Latency", "Bandwidth", "Throughput", "Packet Loss"], "difficulty": "green" },
  { "category": "Virtualization", "words": ["Hypervisor", "VM", "Container", "Snapshot"], "difficulty": "green" }
];
